### ISSUE TITLE
A how to...

### ISSUE THREAD

**Issue by coldes** [trgraglia/jquery.horizonScroll.js#1]
Have added this to create a "back to" page 1

```
$(document).ready(function(){
  $("button.home").click(function() {
    $('section').horizon('scrollTo', '0');
  });
});
```

And in last html section page added
`<button class="home" type="button">PAGE 1</button>`

This works, however on this back to scroll, page one shows both L/R arrows, the L arrow on click scrolls back to 2nd last section, and R arrow not active, ie they are still bound to the last section page

My question, is how to have page 1 showing only the R arrow that is bound to scroll to next section page [ie page 2]

Also, I am trying to implement a lazy load for each page which is loaded using .onload, however I am using a binding click via 'horizon-next' which means all section pages load all images
`<div class="horizon-next"><a href="javascript:void(0);" class="pg2 pg3"><img src="images/r-arrow.png"></a></div>`

```
$(".pg2").click(function() {
    $("#loadpage2").load("page2.html");
});
$(".pg3").click(function() {
    $("#loadpage3").load("page3.html");
});
```

What I am wanting is only that section page in view to load images

fyi I am using a plugin from [http://jquery.eisbehr.de/lazy/]

Any assistance will be greatly appreciated

thank you, Col

**Comment by trgraglia** [comment]
If it is scrolling back to the second to last screen, then 'i' is not being set to zero. Try your line without quotes around zero. $('section').horizon('scrollTo', 0);

**Comment by coldes** [comment]
..thank you that worked, scrolling from last page back to first,  however the R arrow on first page [after this scroll back] is not triggering scroll to page 2, thoughts?...

console only shows:
Scroll right

where I see from previous console log, should be
Scroll right
Scroll to: 1

**Comment by trgraglia** [comment]
i is not being set. That's a bug. Ill look at it right now.

**Comment by trgraglia** [comment]
Sorry for the delay. Version 1.0.3 has a fix for your issue. Thanks for raising it.
