### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by agerber23** [trgraglia/jquery.horizonScroll.js#3]
Hey, does this plugin have any support for browsing on mobile devices?

**Comment by trgraglia** [comment]
Swiping is supported via jquery.swipeTouch.js.

It can be disabled if you like. (Check out the <a href="https://github.com/trgraglia/jquery.horizonScroll.js">readme</a>)

**Comment by agerber23** [comment]
Hi, I meant when I viewed the demo (http://trgraglia.github.io/jquery.horizonScroll.js/demo/index.html) on mobile (iOS), everything was shrunk down and wasn't letting me swipe (all four colors show up on the first page in safari). I was wondering if this was generally more supported for desktop only, or if there were extra steps to get the demo to render nicely on mobile.

Let me know! Thanks.

**Comment by agerber23** [comment]
By the way, if anyone is curious, on ios9 there is a bug that causes this to render incorrectly. Here's the meta tag that got it to work for me, sorry for the late update: 

`<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no, shrink-to-fit=no">`

**Comment by lifeelement** [comment]
The swipe doesn't work in IE.

**Comment by agerber23** [comment]
Which version? @lifeelement

**Comment by lifeelement** [comment]
11

**Comment by lifeelement** [comment]
The scrolling works by button click, but not the swiping. I'm using Windows
10 on a touch screen device.

**Comment by lifeelement** [comment]
Could you provide an example of the 'scrollTo' method? Using the $(document).horizon('scrollTo', i); doesn't seem to be working. With the demo provided and adding a button to that demo to navigate to the second index, how should this be done?

**Comment by trgraglia** [comment]
With the mouse it works... I dont have a touchscreen win10 device. Can anyone else reproduce this?
